### ISSUE TITLE
Problem inserting new group

### ISSUE THREAD

**Issue by PatriciaFonseca** [ELDAELRA/ELRI#111]
When creating a group using the "edit user" page, the group will not be available on "groups".

**Comment by tetchegoyhen** [comment]
Please provide more information regarding this issue, since groups are not created via "edit user" but via Administration->Groups.  Were the steps you followed the ones in the Maintainer Manual?

**Comment by PatriciaFonseca** [comment]
When I'm creating a new user and reached the groups section, I try to add a new one (nonexistent), the problem is that it creates the new group in there but in the group menu it does not appear.

I noticed that when we created a group through the menu administration -> groups this problem does not happen, however we wanted to test this button to add a group when we created a user.

**Comment by tetchegoyhen** [comment]
Thanks for the clarification. This scenario is not currently contemplated in the guidelines for group creation, so I suggest we leave this issue aside for now and only consider issues that related to the NRS management guidelines (group creation in this case).
