### ISSUE TITLE
URLs on site without ELRI_LANGUAGE prefix

### ISSUE THREAD

**Issue by gpfconway** [ELDAELRA/ELRI#139]
Number of URLs on homepage do not have ELRI_LANGUAGE prefix.
This causes Nginx to throw 404 due to Joao's redirect fix in DCU-R2.6 #69 
On front page:
Register: https://elri.computing.dcu.ie/accounts/create
Sign-in: https://elri.computing.dcu.ie/login
Browse: https://elri.computing.dcu.ie/repository/search
Contribute: https://elri.computing.dcu.ie/repository/contribute
Also privacy link in Cookie notification.
Links work from main menu:
https://elri.computing.dcu.ie/en-ie/legal/#Privacy
But some internal links causing issues because of redirect fix. Password change throws 404 after change due to URL:
https://elri.computing.dcu.ie/accounts/profile/change_password/done/
Also believe this is related to why our uploads don't work. Some internal URL without ELRI_LANGUAGE prefix.

**Comment by gpfconway** [comment]
Reverting back to image: elrinrs/nginx:R2.3 works.

**Comment by tetchegoyhen** [comment]
Hi João, 

Could you take a look at this? The app is not functional with Nginx 2.4 but works fine with 2.3, and this seems to be related to the forced redirection fix (see Gary's comment above).

Thanks,

Thierry

**Comment by jcorteslinkare** [comment]
Can you clarify if is it supposed to exist links without the language prefix? Should not both Irish and Gaelic have the same behavior?

Either case, i am trying with the latest version of DCU branch and i am getting the same behaviour with both nginx R2.3 and R2.4 images...

**Comment by jcorteslinkare** [comment]
Sorry i forgot to mention that the same behavior is failing with a 404 when accessing the gaelic option

**Comment by jcorteslinkare** [comment]
Have you tried to add the property to nrs_secret.properties this way?:

ELRI_LOC_LANGUAGES=[("ga-ie"),("en-ie")]

The 404 errors does not occur this way in R2.4.

Best regards,
João Cortes

**Comment by gpfconway** [comment]
Hi João,
I have re-deployed our ELRI with nginx 2.4 and your suggestion:
ELRI_LOC_LANGUAGES=[("ga-ie"),("en-ie")]
I still get 404 from the homepage and internal links. You can test yourself:
https://elri-prd.computing.dcu.ie/en-ie/
Click on Sign-In at the bottom of homepage.
=====================================
localadm@elri-r740:~/compose.DCU_R3.1$ cat nrs_secret.properties
ELRI_TIMEZONE=Europe/Dublin
ELRI_LANGUAGE=ga-ie
ELRI_SALT=jll4l3vofub793po70db34cjm52pec8a
ELRI_ALERT_MAILS=elri@computing.dcu.ie
ELRI_COUNTRY=Ireland
ELRI_EMAIL_TLS=True
ELRI_EMAIL_HOST=mailhost.computing.dcu.ie
ELRI_EMAIL_PORT=587
ELRI_EMAIL_USER=elri
ELRI_EMAIL_PASS=ty6mE2VI
ELRI_LOC_LANGUAGES=[("ga-ie"),("en-ie")]
ELRI_SUP_LANGUAGES=[("English", "English"), ("French", "French"), ("German", "German"), ("Italian", "Italian"), ("Irish", "Irish"), ("Spanish; Castilian", "Spanish"), ("Portuguese", "Portuguese")]
ELRI_EMAIL_ADDRESSES=elri-nrs-support:elri@computing.dcu.ie,elri-no-reply:no-reply-elri@computing.dcu.ie,elri-ilsp:elri@computing.dcu.ie,elri-edelivery:elri@computing.dcu.ie
ELRI_WORKERS=2
ELRI_THREADS=4
localadm@elri-r740:~/compose.DCU_R3.1$ grep image docker-compose.yml
    image: elrinrs/nationalrelaystation:DCU_R3.1
    image: elrinrs/nginx:R2.4
    image: elrinrs/postgres-server:R1
    image: elrinrs/solr:R1
    image: elrinrs/toolchain:R3.1
localadm@elri-r740:~/compose.DCU_R3.1
===========================================
elri_webserver     | 136.206.11.22 - - [26/Mar/2019:11:20:10 +0000] "GET /jsi18n/ HTTP/1.1" **404** 548 "https://elri-prd.computing.dcu.ie/en-ie/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "-"
===========================================

**Comment by jcorteslinkare** [comment]
Oh, now i understand, i was thinking that the links were the ones on top.

Would it not be easier that this links use the same approach as the top buttons? I am not seeing an easy way to do that kind of nginx redirection specially in this case that we must choose between 2 different languages...

**Comment by jcorteslinkare** [comment]
As i see in the django.po files, the href used is /elri:

metashare/templates/locale/pt_PT/LC_MESSAGES/django.po:#| "<a href=\"**/elri**/accounts/create\">Register</a> to become a member of "

I can also /elri to /ELRI_LANGUAGE, but in this case, the irish page will send the users to the gaelic page.

An alternative could be changing the po files to use something like:

metashare/templates/locale/pt_PT/LC_MESSAGES/django.po:#| "<a href=\"**/pt-pt**/accounts/create\">Register</a> to become a member of "

But this would mean changing all po files for every country...

**Comment by tetchegoyhen** [comment]
Eva took a look at this issue as well, and it's indeed a .po issue. it seems that for a while now the .po files for some languages, not all, have added /elri/ in the translation, which won't work but the link apparently hadn't been checked yet...

So, there is no need to change all .po files (the Spanish version works fine for instance), only correct the translations for Ireland and Portugal, leaving the link in the source as is.

**Comment by emartinezvic** [comment]
This was fixed with the new language switch for DCU branch and with the update of the .po files.
Using nginx:R2.3 
Closing
