### ISSUE TITLE
UC010: Branch LR

### ISSUE THREAD

**Issue by popescuv** [ELDAELRA/ELRI#18]
The System should automatically analyse each uploaded file (see also issue https://github.com/ELDAELRA/ELRI/issues/15) and, if deemed automatically processable via the toolchain, place it in the appropriate folder (whence making the file accessible to UC004); else, place it in a distinct folder for manual validation (whence making the file accessible to UC013).

**Comment by emartinezvic** [comment]
closed by  [10bfef6](https://github.com/ELDAELRA/ELRI/commit/10bfef6d51b4142e96960b1bfe3cf1a85bc2a9d9)
