### ISSUE TITLE
Cannot pull elrinrs/toolchain Docker image

### ISSUE THREAD

**Issue by msinkec** [ELDAELRA/ELRI#186]
I'm trying to deploy ELRI with Docker, however I can't pull the toolchain image.

I get the following output from Docker:
```
$ docker pull elrinrs/toolchain:R3.8

Error response from daemon: pull access denied for elrinrs/toolchain, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by tetchegoyhen** [comment]
Access to the toolchain repository is restricted, as they are licensed under condition to the funding agency and deployment of a complete NRS in new countries is controlled under the governance plan of the project. Please contact the ELRI team at the address indicated in wwww.elri-project.eu for further information.
