### ISSUE TITLE
UC004 - Prepare resources: Triggering condition

### ISSUE THREAD

**Issue by popescuv** [ELDAELRA/ELRI#22]
A "Prepare selected ingested resources" action needs to be added and made accessible to the Reviewers, on the "Manage all Resources" page.

This action will trigger the actual resource preparation workflow.

**Comment by emartinezvic** [comment]
closed by  [10bfef6](https://github.com/ELDAELRA/ELRI/commit/10bfef6d51b4142e96960b1bfe3cf1a85bc2a9d9)
