### ISSUE TITLE
UC004: Resource preparation workflow

### ISSUE THREAD

**Issue by popescuv** [ELDAELRA/ELRI#23]
This UC has the effect of:
- keeping the original resource in the "Ingested" state
- creating a new, processed resource, in the "Internal" state.

To this end, the following steps need to be implemented, for a resource in the "Ingested" state and selected for preparation:
- for TMX input files in the appropriate folder: call into the toolchain to:
  - clean boilerplate and noisy aligned TUs
  - produce a TMX 1.4b file and move it to the appropriate folder
- for input files in other accepted formats (see Issue #15):
  - for monolingual data:
    - produce UTF-8-encoded text file with sentence-split content and word count information
    - store word count information in a `basename_mono_wordcount.language` text file.
  - for multilingual data:
    - convert each document in a UTF-8-encoded text file
    - identify the language of each document, assuming that each document is in a single language
    - group documents by identified languages and compute language pairs for the languages specified by the Data Holder or by the Reviewer in the resource metadata
    - pre-process the files
    - align the documents for all computed language pairs
    - align the sentences for each pair of aligned documents
    - produce a TMX 1.4b file and move it to the appropriate folder
- create new resource and set its status to "Internal".

The toolchains communicate with the app via a JSON RESTful API.

**Comment by emartinezvic** [comment]
closed by  [10bfef6](https://github.com/ELDAELRA/ELRI/commit/10bfef6d51b4142e96960b1bfe3cf1a85bc2a9d9)
