### ISSUE TITLE
UC004: resource preparation success e-mail notification

### ISSUE THREAD

**Issue by popescuv** [ELDAELRA/ELRI#24]
Upon successful completion of the workflow described in Issue #22, the System sends an e-mail notification to the contact user (the Data Holder) of the primary resource.

**Comment by emartinezvic** [comment]
More specifically: upon successful completion of the workflow, the System needs to send an email to the Reviewer(s), so the resource can then be eventually published. After the LR is published, an email should be sent to the data holder (uploader of resource) to notify them of the completion of the process.

**Comment by emartinezvic** [comment]
E-mail sending tested using a Postfix SMTP mail built-in service. 
Needs to configure EMAIL_USE_TLS, EMAIL_HOST, EMAIL_POST, EMAIL_HOST_USER and EMAIL_HOST_PASSWORD variables in local_settings.py .
Closed in #49 .
