### ISSUE TITLE
Update page contents for ELRI

### ISSUE THREAD

**Issue by popescuv** [ELDAELRA/ELRI#3]
Thus, replace references to ELRC-SHARE with references to ELRI.

**Comment by popescuv** [comment]
The elri_vic branch merge onto master has addressed a significant portion of this issue.

**Comment by emartinezvic** [comment]
closed by #37

**Comment by tetchegoyhen** [comment]
There are still some references to ELRC-SHARE that should be replaced with ELRI, e.g. tab titles. A systematic search and review should be performed.

**Comment by tetchegoyhen** [comment]
Fixed on VIC branch, will be closed when merged with MASTER.

**Comment by tetchegoyhen** [comment]
Still at least one left, see pre-issue 18:

Browse tab - the top of the tab reads Search and Browse ELRC SHARE
Edit Profile for a user  - the top of the tab reads Edit Profile ELRC SHARE
All other menus show ELRI on the tab.

**Comment by emartinezvic** [comment]
closed in release R2.4
