### ISSUE TITLE
Login error (500)

### ISSUE THREAD

**Issue by tetchegoyhen** [ELDAELRA/ELRI#35]
On a fresh pull from the master branch (2018-10-23, 10:00AM CEST), we get the login errors below. This does not happen on the elri_vic branch version of the webapp.

1. From the login page, attempting to log in as super user results in Internal Server Error (500). Creating a new super user via "python manage.py createsuperuser" triggers the same error. 

The trace of the error is:

> [10/23/2018 @ 10:38:44] metashare.views::INFO Rendering login view for user "Anonymous".
> [10/23/2018 @ 10:38:44] django.request::ERROR Internal Server Error: /en/elri/login/
> Traceback (most recent call last):
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/data/mt/ELRI/metashare/views.py", line 34, in login
>     return LOGIN(request, template_name)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
>     return view(request, *args, **kwargs)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/contrib/auth/views.py", line 44, in login
>     auth_login(request, form.get_user())
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 103, in login
>     user_logged_in.send(sender=user.__class__, request=request, user=user)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
>     response = receiver(signal=self, sender=sender, **named)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 26, in update_last_login
>     user.save(update_fields=['last_login'])
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
>     force_update=force_update, update_fields=update_fields)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 626, in save_base
>     update_fields=update_fields, raw=raw, using=using)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
>     response = receiver(signal=self, sender=sender, **named)
>   File "/data/mt/ELRI/metashare/accounts/models.py", line 397, in create_profile
>     profile = instance.userprofile
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 418, in __get__
>     rel_obj = self.get_queryset(instance=instance).get(**params)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
>     num = len(clone)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
>     self._fetch_all()
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
>     self._result_cache = list(self.iterator())
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
>     for row in compiler.results_iter():
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
>     for rows in self.execute_sql(MULTI):
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
>     cursor.execute(sql, params)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
>     return self.cursor.execute(sql, params)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/data/mt/ELRI/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
>     return self.cursor.execute(sql, params)
> ProgrammingError: column accounts_userprofile.affiliation_address does not exist
> LINE 1: ...."country", "accounts_userprofile"."affiliation", "accounts_...
> 

2. On retry after the error in 1, we get: Forbidden (403) CSRF verification failed. Request aborted.

> [10/23/2018 @ 10:38:57] metashare.views::INFO Rendering login view for user "Anonymous".
> [10/23/2018 @ 10:38:57] django.request::WARNING Forbidden (CSRF token missing or incorrect.): /en/elri/login/
> [23/Oct/2018 10:38:57] "POST /en/elri/login/ HTTP/1.1" 403 1007

**Comment by popescuv** [comment]
You need to issue the following two commands before being able to use the app with the HEAD of the master branch, as indicated in the commit message of changeset 6e8be92c1eed8c40ff5db977ee39d1b400988d78:

- python manage.py makemigrations accounts
- python manage.py migrate accounts
