### ISSUE TITLE
UC001: lagging Domain hovering tooltip 

### ISSUE THREAD

**Issue by emartinezvic** [ELDAELRA/ELRI#43]
When hovering over Domain information the transition between one tooltip and the other results in overlapping unreadable information.

**Comment by luismsgomes** [comment]
Is this in the resource metadata view or in the metadata editor?
Which browser did you use?
I could not reproduce the error here (using Firefox):
- in the metadata view, no tooltip appears
- in the metadata editor, the tooltips appear but they do not overlap

**Comment by emartinezvic** [comment]
This issue refers to the Domain tooltip in the contribute.html template here: [ELRI/metashare/templates/repository/editor/contributions/contribute.html](ELRI/metashare/templates/repository/editor/contributions/contribute.html).

**Comment by tetchegoyhen** [comment]
The issue is fixed on the FCUL branch and we will close it once the branch is merged with the MASTER.
