### ISSUE TITLE
UI icons do not show in low resolution screens

### ISSUE THREAD

**Issue by emartinezvic** [ELDAELRA/ELRI#46]
Allow users with screen resolution lower than full HD to see the menu icons.

**Comment by aazpeitia** [comment]
Setting `display: inline` property in `metashare/templates/header.html` to the `<div class)="jsddm">` element puts the menu in two lines if occurs an overflow:

![elri_icon_inline](https://user-images.githubusercontent.com/3336935/51933409-8ff0c900-2401-11e9-90f2-7a8f9adbcd9a.png)

This could be an easy solution.

**Comment by aazpeitia** [comment]
Menu bar is now changed depending on the screen width:

- `width ≥ 1000px`
![menu1](https://user-images.githubusercontent.com/3336935/52801769-e35c4b80-307e-11e9-889d-c1e0e59da3ed.png)
![menu2](https://user-images.githubusercontent.com/3336935/52801805-f66f1b80-307e-11e9-9fdc-518865bf8a82.png)
- `width < 1000px`
![menu3](https://user-images.githubusercontent.com/3336935/52801824-0555ce00-307f-11e9-9d54-b2ada82b2bdb.png)

All this changes have been done in commit https://github.com/ELDAELRA/ELRI/commit/7902dc150e03459696db4233d68bcef7e07d6414
