### ISSUE TITLE
Error in Setup step 5: TypeError: ugettext() got an unexpected keyword argument 'help_text'

### ISSUE THREAD

**Issue by emartinezvic** [ELDAELRA/ELRI#7]
We get this error: `TypeError: ugettext() got an unexpected keyword argument 'help_text' `
when executing the 5th step of the SetUp. 

I paste here the output and the error trace:

> ELRI$ python manage.py makemigrations accounts repository stats recommendations storage 
Migrations for 'accounts':
  0001_initial.py:
    - Create model AccessPointEdeliveryApplication
    - Create model EditorGroup
    - Create model EditorGroupApplication
    - Create model EditorGroupManagers
    - Create model Organization
    - Create model OrganizationApplication
    - Create model OrganizationManagers
    - Create model RegistrationRequest
    - Create model ResetRequest
    - Create model UserProfile
Migrations for 'repository':
  0001_initial.py:
    - Create model actorInfoType_model
    - Create model annotationInfoType_model
    - Create model characterEncodingInfoType_model
    - Create model communicationInfoType_model
    - Create model corpusMediaTypeType_model
    - Create model corpusTextInfoType_model
    - Create model creationInfoType_model
    - Create model dependenciesInfoType_model
    - Create model distributionInfoType_model
    - Create model documentationInfoType_model
    - Create model documentInfoType_model
    - Create model documentUnstructuredString_model
    - Create model domainInfoType_model
    - Create model domainSetInfoType_model
    - Create model identificationInfoType_model
    - Create model inputInfoType_model
    - Create model languageDescriptionEncodingInfoType_model
    - Create model languageDescriptionMediaTypeType_model
    - Create model languageDescriptionTextInfoType_model
    - Create model languageInfoType_model
    - Create model languageSetInfoType_model
    - Create model languageVarietyInfoType_model
    - Create model lexicalConceptualResourceEncodingInfoType_model
    - Create model lexicalConceptualResourceMediaTypeType_model
    - Create model lexicalConceptualResourceTextInfoType_model
    - Create model licenceInfoType_model
    - Create model lingualityInfoType_model
    - Create model metadataInfoType_model
    - Create model organizationInfoType_model
    - Create model outputInfoType_model
    - Create model personInfoType_model
    - Create model projectInfoType_model
    - Create model relationInfoType_model
    - Create model resourceComponentTypeType_model
    - Create model lexicalConceptualResourceInfoType_model
    - Create model languageDescriptionInfoType_model
    - Create model corpusInfoType_model
    - Create model resourceCreationInfoType_model
    - Create model resourceDocumentationInfoType_model
    - Create model resourceInfoType_model
    - Create model sizeInfoType_model
    - Create model targetResourceInfoType_model
    - Create model textClassificationInfoType_model
    - Create model textFormatInfoType_model
    - Create model toolServiceCreationInfoType_model
    - Create model toolServiceEvaluationInfoType_model
    - Create model toolServiceInfoType_model
    - Create model toolServiceOperationInfoType_model
    - Create model validationInfoType_model
    - Create model versionInfoType_model
    - Add field toolServiceOperationInfo to toolserviceinfotype_model
    - Add field resourceComponentType to resourceinfotype_model
    - Add field resourceCreationInfo to resourceinfotype_model
    - Add field resourceDocumentationInfo to resourceinfotype_model
    - Add field storage_object to resourceinfotype_model
    - Add field versionInfo to resourceinfotype_model
    - Add field back_to_resourceinfotype_model to relationinfotype_model
    - Add field relatedResource to relationinfotype_model
    - Add field metadataCreator to metadatainfotype_model
    - Add field lingualityInfo to lexicalconceptualresourcetextinfotype_model
    - Add field lexicalConceptualResourceTextInfo to lexicalconceptualresourcemediatypetype_model
    - Add field lexicalConceptualResourceMediaType to lexicalconceptualresourceinfotype_model
    - Add field sizePerLanguageVariety to languagevarietyinfotype_model
    - Add field back_to_outputinfotype_model to languagesetinfotype_model
    - Add field back_to_lexicalconceptualresourcetextinfotype_model to languageinfotype_model
    - Add field languageVarietyInfo to languageinfotype_model
    - Add field sizePerLanguage to languageinfotype_model
    - Add field lingualityInfo to languagedescriptiontextinfotype_model
    - Add field languageDescriptionTextInfo to languagedescriptionmediatypetype_model
    - Add field languageDescriptionMediaType to languagedescriptioninfotype_model
    - Add field back_to_languagedescriptiontextinfotype_model to domaininfotype_model
    - Add field back_to_lexicalconceptualresourcetextinfotype_model to domaininfotype_model
    - Add field sizePerDomain to domaininfotype_model
    - Add field back_to_resourceinfotype_model to distributioninfotype_model
    - Add field iprHolder to distributioninfotype_model
    - Add field licenceInfo to distributioninfotype_model
    - Add field requiredLRs to dependenciesinfotype_model
    - Add field requiredSoftware to dependenciesinfotype_model
    - Add field creationTool to creationinfotype_model
    - Add field originalSource to creationinfotype_model
    - Add field creationInfo to corpustextinfotype_model
    - Add field lingualityInfo to corpustextinfotype_model
    - Add field back_to_corpustextinfotype_model to characterencodinginfotype_model
    - Add field back_to_languagedescriptiontextinfotype_model to characterencodinginfotype_model
    - Add field back_to_lexicalconceptualresourcetextinfotype_model to characterencodinginfotype_model
    - Add field sizePerCharacterEncoding to characterencodinginfotype_model
    - Add field annotationManual to annotationinfotype_model
    - Add field annotationTool to annotationinfotype_model
    - Add field back_to_corpustextinfotype_model to annotationinfotype_model
    - Add field sizePerAnnotation to annotationinfotype_model
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 124, in handle
    self.write_migration_files(changes)
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 152, in write_migration_files
    migration_string = writer.as_string()
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 131, in as_string
    operation_string, operation_imports = OperationWriter(operation).serialize()
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 82, in serialize
    arg_string, arg_imports = MigrationWriter.serialize(item)
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 263, in serialize
    item_string, item_imports = cls.serialize(item)
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 333, in serialize
    return cls.serialize_deconstructed(path, args, kwargs)
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 239, in serialize_deconstructed
    arg_string, arg_imports = cls.serialize(arg)
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/db/migrations/writer.py", line 256, in serialize
    value = force_text(value)
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/utils/encoding.py", line 85, in force_text
    s = six.text_type(s)
  File "/home/VICOMTECH/emartinez/git/ELDA_ELRA2/ELRI/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 144, in __text_cast
    return func(*self.__args, **self.__kw)
TypeError: ugettext() got an unexpected keyword argument 'help_text'

**Comment by popescuv** [comment]
One commit has done to fix an i18n mechanics integration bug.
