### ISSUE TITLE
Configuration set at /etc/nginx/nginx.conf - Best pratices

### ISSUE THREAD

**Issue by jcorteslinkare** [ELDAELRA/ELRI#70]
It is not the best pratice to set options directly at the /etc/nginx/nginx.conf.

Can you tell the error that occurs when this option is not set so i can test if this can be set at the vhost file?

**Comment by emartinezvic** [comment]
When the option is not set at the nginx.conf the upload file size limit is set to 1MB, so a user cannot upload big lr documents to the system.
Setting it directly at the nginx.conf file was a quick solution.
Could you please test  the alternative of setting it at the vhost file?
Thanks!

**Comment by jcorteslinkare** [comment]
Hi Eva,

Can you try with the nginx image i pushed (R2.2)?

If all is good i will commit the changes.

**Comment by emartinezvic** [comment]
I tested the webapp using the nginx R2.2 image and it works :) 

thank you very much!

**Comment by jcorteslinkare** [comment]
Changes commited :), closing the issue
