### ISSUE TITLE
Display errors with bilingual switch

### ISSUE THREAD

**Issue by tetchegoyhen** [ELDAELRA/ELRI#77]
With the bilingual switch added to the menu header, the top of the pages are not visible anymore, e.g. the actions menu in the Change resource page.

**Comment by emartinezvic** [comment]
This is how it is seen now, under the Management-> Manage all resources (for a superuser/reviewer user):
 
![dcu_lr_manage](https://user-images.githubusercontent.com/34244755/52787689-e8a99e00-305e-11e9-9a24-0046b3f52df5.png)

and this is how it should be seen: 

![elri_lr_manage](https://user-images.githubusercontent.com/34244755/52787708-f5c68d00-305e-11e9-9a89-e1a263b70f0b.png)

Note that there is missing the Actions on Resource menu which is almost essential for the reviewers work.

**Comment by DariaD** [comment]
Dear all,

Thank you very much for all the details.
During the call yesterday it was mentioned that a similar problem had happened before.
Could you provide a bit of information about how did you fix it last time?
