### ISSUE TITLE
Verify Django cookies

### ISSUE THREAD

**Issue by tetchegoyhen** [ELDAELRA/ELRI#96]
The ELRI NRS policy is to not use cookies, but Django does. We need to remove the setting of cookies by Django if possible or verify that they are necessary for the NRS.

**Comment by hpusset** [comment]
We have 2 cookies related to Django application.
- `sessionid` used by SessionMiddleware and authentication, we can't remove it and use authentication.
- `csrftoken` used with form for security when you submited POST request form.

**Comment by tetchegoyhen** [comment]
Hi Hervé, if you agree with this, we should leave these two cookies and close the issue. Eva has added a cookies-related disclaimer for users in our branch and we'll merge it to the Master.
